=== api-evangelist/clerk-com/json-schema/clerk-oauthapplication-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/clerk-com/main/json-schema/clerk-oauthapplication-schema.json",
  "title": "Clerk OAuthApplication",
  "description": "Clerk OAuthApplication object.",
  "type": "object",
  "properties": {
    "object": {
      "type": "string",
      "enum": [
        "oauth_application"
      ]
    },
    "id": {
      "type": "string"
    },
    "instance_id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "client_id": {
      "type": "string"
    },
    "client_uri": {
      "type": "string",
      "nullable": true
    },
    "client_image_url": {
      "type": "string",
      "nullable": true
    },
    "dynamically_registered": {
      "type": "boolean"
    },
    "consent_screen_enabled": {
      "type": "boolean"
    },
    "pkce_required": {
      "type": "boolean"
    },
    "public": {
      "type": "boolean"
    },
    "scopes": {
      "type": "string"
    },
    "redirect_uris": {
      "type": "array",
      "items": {
        "type": "string"
      }
    },
    "callback_url": {
      "type": "string",
      "deprecated": true,
      "description": "Deprecated: Use redirect_uris instead.\n"
    },
    "authorize_url": {
      "type": "string"
    },
    "token_fetch_url": {
      "type": "string"
    },
    "user_info_url": {
      "type": "string"
    },
    "discovery_url": {
      "type": "string"
    },
    "token_introspection_url": {
      "type": "string"
    },
    "created_at": {
      "type": "integer",
      "format": "int64",
      "description": "Unix timestamp of creation.\n"
    },
    "updated_at": {
      "type": "integer",
      "format": "int64",
      "description": "Unix timestamp of last update.\n"
    }
  },
  "required": [
    "object",
    "id",
    "instance_id",
    "name",
    "dynamically_registered",
    "consent_screen_enabled",
    "pkce_required",
    "public",
    "client_id",
    "client_uri",
    "client_image_url",
    "scopes",
    "redirect_uris",
    "callback_url",
    "authorize_url",
    "token_fetch_url",
    "user_info_url",
    "discovery_url",
    "token_introspection_url",
    "created_at",
    "updated_at"
  ]
}

=== api-evangelist/clerk-com/examples/clerk-oauthapplication-example.json
{
  "object": "oauth_application",
  "id": "example",
  "instance_id": "ins_2abc4xyz567Q9zZdEf",
  "name": "Acme Corp",
  "client_id": "client_2abc4xyz567Q9zZdEf",
  "client_uri": "example",
  "client_image_url": "example",
  "dynamically_registered": false,
  "consent_screen_enabled": false,
  "pkce_required": false,
  "public": false,
  "scopes": "example",
  "redirect_uris": [
    "example"
  ],
  "callback_url": "example",
  "authorize_url": "example",
  "token_fetch_url": "example",
  "user_info_url": "example",
  "discovery_url": "example",
  "token_introspection_url": "example",
  "created_at": 0,
  "updated_at": 0
}
