=== api-evangelist/clerk-com/json-schema/clerk-organization-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/clerk-com/main/json-schema/clerk-organization-schema.json",
  "title": "Clerk Organization",
  "description": "Clerk Organization object.",
  "type": "object",
  "properties": {
    "object": {
      "type": "string",
      "enum": [
        "organization"
      ]
    },
    "id": {
      "type": "string"
    },
    "name": {
      "type": "string"
    },
    "slug": {
      "type": "string"
    },
    "image_url": {
      "type": "string"
    },
    "has_image": {
      "type": "boolean"
    },
    "members_count": {
      "type": "integer"
    },
    "missing_member_with_elevated_permissions": {
      "type": "boolean"
    },
    "pending_invitations_count": {
      "type": "integer"
    },
    "max_allowed_memberships": {
      "type": "integer"
    },
    "admin_delete_enabled": {
      "type": "boolean"
    },
    "public_metadata": {
      "type": "object",
      "additionalProperties": true
    },
    "private_metadata": {
      "type": "object",
      "additionalProperties": true
    },
    "created_by": {
      "type": "string"
    },
    "created_at": {
      "type": "integer",
      "format": "int64",
      "description": "Unix timestamp of creation.\n"
    },
    "updated_at": {
      "type": "integer",
      "format": "int64",
      "description": "Unix timestamp of last update.\n"
    },
    "last_active_at": {
      "type": "integer",
      "format": "int64",
      "description": "Unix timestamp of last activity.\n"
    },
    "role_set_key": {
      "type": "string",
      "description": "The key of the [role set](https://clerk.com/docs/guides/organizations/control-access/role-sets) assigned to this organization.\n",
      "nullable": true
    }
  },
  "required": [
    "object",
    "id",
    "name",
    "slug",
    "has_image",
    "max_allowed_memberships",
    "admin_delete_enabled",
    "public_metadata",
    "created_at",
    "updated_at"
  ]
}

=== api-evangelist/clerk-com/examples/clerk-organization-example.json
{
  "object": "organization",
  "id": "example",
  "name": "Acme Corp",
  "slug": "acme-corp",
  "image_url": "example",
  "has_image": false,
  "members_count": 1,
  "missing_member_with_elevated_permissions": false,
  "pending_invitations_count": 1,
  "max_allowed_memberships": 0,
  "admin_delete_enabled": false,
  "public_metadata": {},
  "private_metadata": {},
  "created_by": "example",
  "created_at": 0,
  "updated_at": 0,
  "last_active_at": 0,
  "role_set_key": "example"
}
