=== api-evangelist/clerk-com/json-schema/clerk-session-schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "$id": "https://raw.githubusercontent.com/api-evangelist/clerk-com/main/json-schema/clerk-session-schema.json",
  "title": "Clerk Session",
  "description": "Clerk Session object.",
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "object": {
      "type": "string",
      "description": "String representing the object's type. Objects of the same type share the same value.\n",
      "enum": [
        "session"
      ]
    },
    "id": {
      "type": "string"
    },
    "user_id": {
      "type": "string"
    },
    "client_id": {
      "type": "string"
    },
    "actor": {
      "type": "object",
      "nullable": true
    },
    "status": {
      "type": "string",
      "enum": [
        "active",
        "revoked",
        "ended",
        "expired",
        "removed",
        "abandoned",
        "replaced",
        "pending"
      ]
    },
    "last_active_organization_id": {
      "type": "string",
      "nullable": true
    },
    "last_active_at": {
      "type": "integer"
    },
    "latest_activity": {
      "type": "object",
      "nullable": true,
      "properties": {
        "object": {
          "type": "string"
        },
        "id": {
          "type": "string"
        },
        "device_type": {
          "type": "string"
        },
        "is_mobile": {
          "type": "boolean"
        },
        "browser_name": {
          "type": "string"
        },
        "browser_version": {
          "type": "string"
        },
        "ip_address": {
          "type": "string"
        },
        "city": {
          "type": "string"
        },
        "country": {
          "type": "string"
        }
      },
      "required": [
        "id",
        "object",
        "is_mobile"
      ]
    },
    "expire_at": {
      "type": "integer",
      "format": "int64",
      "description": "Unix timestamp of expiration.\n"
    },
    "abandon_at": {
      "type": "integer",
      "format": "int64",
      "description": "Unix timestamp of abandonment.\n"
    },
    "updated_at": {
      "type": "integer",
      "format": "int64",
      "description": "Unix timestamp of last update.\n"
    },
    "created_at": {
      "type": "integer",
      "format": "int64",
      "description": "Unix timestamp of creation.\n"
    },
    "tasks": {
      "type": "array",
      "nullable": true,
      "items": {
        "type": "object",
        "properties": {
          "key": {
            "type": "string"
          }
        },
        "required": [
          "key"
        ]
      }
    }
  },
  "required": [
    "object",
    "id",
    "user_id",
    "client_id",
    "status",
    "last_active_at",
    "expire_at",
    "abandon_at",
    "updated_at",
    "created_at"
  ]
}

=== api-evangelist/clerk-com/examples/clerk-session-example.json
{
  "object": "session",
  "id": "example",
  "user_id": "user_2abc4xyz567Q9zZdEf",
  "client_id": "client_2abc4xyz567Q9zZdEf",
  "actor": {},
  "status": "active",
  "last_active_organization_id": "org_2abc4xyz567Q9zZdEf",
  "last_active_at": 0,
  "latest_activity": {
    "object": "user",
    "id": "example",
    "device_type": "example",
    "is_mobile": false,
    "browser_name": "example",
    "browser_version": "example",
    "ip_address": "example",
    "city": "example",
    "country": "example"
  },
  "expire_at": 1747939800,
  "abandon_at": 0,
  "updated_at": 0,
  "created_at": 0,
  "tasks": [
    {
      "key": "example"
    }
  ]
}
